### ISSUE TITLE
MarqueeLabel，MTGSDKSplash(MTGMarqueeLabel.o)

### ISSUE THREAD

**Issue by solargalaxy** [Mintegral-official/MintegralAdSDK-iOS-new#10]

**Comment by solargalaxy** [comment]
duplicate symbol '_MLOffsetCGPoint' 
duplicate symbol '_OBJC_CLASS_$_GradientSetupAnimation'

**Comment by red3** [comment]
@solargalaxy thanks for your feedback, we will fix this on the next release.

**Comment by red3** [comment]
Since this issue is resolved, I'll close it.
