### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by ddaddy** [Mintegral-official/MintegralAdSDK-iOS-new#13]
Can we please get support for installing from Swift Package Manager as this is the recommended package manager going forward.

**Comment by red3** [comment]
We'll consider it on future updates.

**Comment by DimDL** [comment]
Would be interested too, any update ? thanks !

**Comment by red3** [comment]
will support it in the recent update and will let you know once released.

**Comment by red3** [comment]
@ddaddy @DimDL we now released the support for spm, please see: https://github.com/Mintegral-official/MintegralAdSDK-Swift-Package, fell free to let me know if you have any problems.
