### ISSUE TITLE
有关台湾地区会访问CN地址的CDN问题

### ISSUE THREAD

**Issue by MonkeyKingMKY** [Mintegral-official/MintegralAdSDK-iOS-new#16]
我们这边沟通技术人员发现

> 这几个ip对应的 [101.200.190.163](http://101.200.190.163/)  [analytics-ios.rayjump.com](http://analytics-ios.rayjump.com/)  ，[123.56.123.203](http://123.56.123.203/) [analytics.mindworks-creative.cn](http://analytics.mindworks-creative.cn/)都是mintegral这个渠道的，跟创意有关。

mintegral 在台湾地区，会连接 CN 地址的 CDN
由于 台湾地区的审查，在最近一段时间，要求 App 中不能访问 CN 地址。
我们经过调查 发现上面的问题，这个 应该如何解决？

**Comment by a4231225520** [comment]
你好，请把问题发送到这个邮箱：developer@mintegral.com
会有技术人员回复你解决方案
