### ISSUE TITLE
Linker warnings

### ISSUE THREAD

**Issue by polmum** [Mintegral-official/MintegralAdSDK-iOS-new#3]
We are getting the following linker warnings when building:
`ld: warning: instance method 'gzippedData' in category from /path/to/Pods/MintegralAdSDK/Fmk/MTGSDK.framework/MTGSDK(NSData+MTGExtension_Compress.o) conflicts with same method from another category
ld: warning: instance method 'gzippedDataWithCompressionLevel:' in category from /path/to/Pods/MintegralAdSDK/Fmk/MTGSDK.framework/MTGSDK(NSData+MTGExtension_Compress.o) conflicts with same method from another category
ld: warning: instance method 'isGzippedData' in category from /path/to/Pods/MintegralAdSDK/Fmk/MTGSDK.framework/MTGSDK(NSData+MTGExtension_Compress.o) conflicts with same method from another category `

**Comment by red3** [comment]
Hi, @polmum , thanks for sharing this, we will fix this issue in the future version.
