### ISSUE TITLE
Can't find framework in Xcode after `pod install`

### ISSUE THREAD

**Issue by Handsome2734** [Mintegral-official/MintegralAdSDK-iOS-new#7]
Below is part of my Podfile
```
  # MTG
  # https://github.com/Mintegral-official/MintegralAdSDK-iOS-new
  pod 'MintegralAdSDK', '6.1.0'
  pod 'MintegralAdSDK/NativeAd'
  pod 'MintegralAdSDK/BidNativeAd'
  pod 'MintegralAdSDK/RewardVideoAd'
  pod 'MintegralAdSDK/BidRewardVideoAd'
  pod 'MintegralAdSDK/InterstitialVideoAd'
  pod 'MintegralAdSDK/BidInterstitialVideoAd'
  pod 'MintegralAdSDK/InterstitialAd'
  pod 'MintegralAdSDK/InterActiveAd'
  pod 'MintegralAdSDK/BannerAd'
  pod 'MintegralAdSDK/BidBannerAd'
  pod 'MintegralAdSDK/SplashAd'
  pod 'MintegralAdSDK/BidSplashAd'
  pod 'MintegralAdSDK/NativeAdvancedAd'
  pod 'MintegralAdSDK/BidNativeAdvancedAd'
```

After I ran `pod install`, everything looks fine, and I can find frameworks in Finder.
However in XCode, I can only find `NativeAds.framework`. How can I resolve this?

![XCode](https://user-images.githubusercontent.com/5567825/99656502-ed06b480-2a97-11eb-8dc0-27b95dfbe8a2.png)
![Finder](https://user-images.githubusercontent.com/5567825/99656594-0e67a080-2a98-11eb-898c-f1b5dba44208.png)

**Comment by red3** [comment]
@Handsome2734 you can contact your account manager and they will help you with this issue.
