### ISSUE TITLE
Build issue on 6.9.5

### ISSUE THREAD

**Issue by stomych** [Mintegral-official/MintegralAdSDK-iOS-new#8]
After adding `MintegralAdSDK (6.9.5.0)` to an empty project (via cocoapods). 
I get these errors
Multiple commands produce 'my_path/Build/Products/Debug_BT-iphonesimulator/XCFrameworkIntermediates/MTGSDKBanner':
1) That command depends on command in Target 'MintegralAdSDK' (project 'Pods'): script phase “[CP] Copy XCFrameworks”
2) That command depends on command in Target 'MintegralAdSDK' (project 'Pods'): script phase “[CP] Copy XCFrameworks”
Multiple commands produce 'my_path/Build/Products/Debug_BT-iphonesimulator/XCFrameworkIntermediates/MTGSDKInterstitialVideo':
1) That command depends on command in Target 'MintegralAdSDK' (project 'Pods'): script phase “[CP] Copy XCFrameworks”
2) That command depends on command in Target 'MintegralAdSDK' (project 'Pods'): script phase “[CP] Copy XCFrameworks”

Multiple commands produce 'my_path/Build/Products/Debug_BT-iphonesimulator/XCFrameworkIntermediates/MTGSDK':
1) That command depends on command in Target 'MintegralAdSDK' (project 'Pods'): script phase “[CP] Copy XCFrameworks”
2) That command depends on command in Target 'MintegralAdSDK' (project 'Pods'): script phase “[CP] Copy XCFrameworks”

Multiple commands produce 'my_path/Build/Products/Debug_BT-iphonesimulator/XCFrameworkIntermediates/MTGSDKReward':
1) That command depends on command in Target 'MintegralAdSDK' (project 'Pods'): script phase “[CP] Copy XCFrameworks”
2) That command depends on command in Target 'MintegralAdSDK' (project 'Pods'): script phase “[CP] Copy XCFrameworks”

**Comment by red3** [comment]
@stomych sorry for the late response, this issue has been fixed on the new 6.9.5.1 version, try `pod update` will solve this issue.

**Comment by stomych** [comment]
Thanks a lot! Works well now!
